### PR TITLE
Fix ActivityPub comments being marked as spam by Akismet

### LINKED ISSUE #2735: Comments on AP Posts: do not hold for moderation
I'm creating this issue to follow-up on #2700, where a bigger issue was revealed:

Comments to `ap_post` post type are not currently always auto-approved, and can be held for moderation. It doesn't make sense for a site owner to have to review and approve comments on conversations of people they follow ; those conversations should appear in their Social Web timeline alongside the others.

Of course, that doesn't mean anything and everything should be displayed in the Social Web timeline. I think the comments should still respect the "Disallowed Comment Keys" field in Discussion settings (`disallowed_keys` option) to allow folks to "mute" terms they do not want to see in their timeline (Related issues: #1589, #2027). 

**This appears to be a bug since #2526 was aiming for those comments to be auto-approved out of the box. **

Maybe the check in https://github.com/Automattic/wordpress-activitypub/blob/bfc5210bc5b27f943542005fc6fb074c54034628/includes/class-comment.php#L771-773 should happen earlier in the method.

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes #2735

## Proposed changes:

* Run `pre_comment_approved` filter at priority 11 (after Akismet's priority 10) so we can override Akismet's spam verdict for authenticated ActivityPub comments
* Fix early return logic to only short-circuit for actually approved comments (`1` or `'1'`), not for `'spam'` or `'trash'` status - previously any truthy value caused an early return

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Install and activate Akismet with an API key
* Receive an ActivityPub comment (like, reply, or announce) from a federated server
* Verify the comment is auto-approved according to your settings, not marked as spam

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch

#### Type

-   [x] Fixed - for any bug fixes

#### Message

Fixed ActivityPub comments being marked as spam by Akismet.

</details>

### CODE REVIEW

**Comment by pfefferle** [comment]
@jeherve if you maybe have a sec to verify my thoughts!?

**Comment by pfefferle** [comment]
At least co-pilot seems to be fine with the changes ;)

File: includes/class-comment.php [hunk 1]
```diff
@@ -731,7 +731,12 @@ public static function comment_query( $query ) {
 	 * @return int|string|\WP_Error The approval status. 1, 0, 'spam', 'trash', or WP_Error.
 	 */
 	public static function pre_comment_approved( $approved, $comment_data ) {
-		if ( $approved || \is_wp_error( $approved ) ) {
+		/*
+		 * Only return early for already-approved comments, trash, or errors.
+		 * Don't short-circuit on 'spam' - we may want to override Akismet.
+		 * Respect 'trash' since it comes from the WordPress disallowed list.
+		 */
+		if ( 1 === $approved || '1' === $approved || 'trash' === $approved || \is_wp_error( $approved ) ) {
```
Comment (jeherve) [inline includes/class-comment.php:739]: Would it make sense to inverse that logic, and instead check if $approved is anything but `spam`?


```suggestion
		if ( 'spam' !== $approved ) {
```

Comment (pfefferle) [reply includes/class-comment.php:739]: what about "pending" (`hold` or `0`)?

Comment (jeherve) [reply includes/class-comment.php:739]: ah my bad, I didn't think about those options!

**Review by jeherve — APPROVED** [review]
