### PR TITLE
Fix sending posts to at most ten instances

### LINKED ISSUE #587: Posts are sent to at most 10 instances
### Quick summary

`WP_Query` paginates by default. This is used to look up the list of inboxes to post to in `Followers::get_inboxes()`, which has the effect of returning at most ten users to post to, which are then deduped on the inbox URL.

### Steps to reproduce

1. Have a profile with more than 10 followers.
2. Make a post.
3. Check where it's delivered to.

### What you expected to happen

All followers should get the post.

### What actually happened

Followers on at most ten instances get the post.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Sentynel**
Fixes #587 

## Proposed changes:

Disable pagination on the query in `Followers::get_inboxes()` that looks up follower IDs. This causes it to return all followers, rather than a paged list of ten of them. This means that we end up delivering our post to all followers, and not to the instances belonging to a subset of ten of them.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* You need an instance with more than ten followers from different instances for a profile (user or blog) to demonstrate the issue here.
* Log outgoing posts in some way.
* Prior to the fix, you'll see that when a post goes out, at most ten instances (and often fewer, if you have more than one follower per instance) actually get sent the message.
* With this fix, all should get them.
* Alternatively, use something like `wp shell` from `wp-cli` to run the queries in before and after fix forms directly and observe the difference.

### CODE REVIEW

**Comment by pfefferle** [comment]
😱 oh no! What a bad bug! thanks a lot for finding it! I definitely have to write some tests for that case!

But I couldn't find the arg `pagination` but `nopaging` instead!?!

Can you verify that?

**Comment by Sentynel** [comment]
Whoops, yes, you're right! Tested it right in the console, immediately copied it down wrong. Don't submit PRs at midnight, folks. Fixed now.

File: includes/collection/class-followers.php [hunk 1]
```diff
@@ -267,6 +267,7 @@ public static function get_inboxes( $user_id ) {
 		// get all Followers of a ID of the WordPress User
 		$posts = new WP_Query(
 			array(
+				'nopaging' => true,
```
Comment (pfefferle) [inline includes/collection/class-followers.php:270]:
```suggestion
				'nopaging'   => true,
```

**Comment by pfefferle** [comment]
Thanks a lot @Sentynel !!!

**Comment by ThisIsMissEm** [comment]
Could similar exist elsewhere, e.g., `Followers::count_followers` or `Followers::get_outdated_followers` and `Followers::get_faulty_followers` (these seem to take per page, but no arguments to actually paginate)?
