### PR TITLE
Fix duplicate follow notifications for existing followers

### LINKED ISSUE #2438: Multiple mails of the same new follower
### Quick summary

I keep getting bulk mails like these for a week now, since a bonfire account is following me. The account also has the name "Bonfire", but I really mean the application bonfire, which is used to host that account. https://bonfire.cafe/@Bonfire

Screenshot of firefox showing multiple emails with title  ew Follower: Bonfire

### Steps to reproduce

Can't. But maybe it's a  _Bonfire_ <-> _WordPress ActivityPub_ issue. So try following a WordPress blog with bonfire.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### PR DESCRIPTION
**Pull request by obenland**
Fixes #2438

**Important Note:** This PR changes what we consider a "successful" follow. Previously, any follow request that didn't error was considered successful. Now, follow requests from actors who are already following are processed but marked as unsuccessful (`$success = false`) to prevent duplicate notifications while still maintaining proper federation behavior.

## Proposed changes:

* Prevent duplicate email notifications when ActivityPub instances re-send Follow activities for actors that are already following
* Check if actor already follows before setting success flag in handle_follow()
* Follow requests from existing followers are now marked as `$success = false` (not successful) to prevent email notifications
* Maintain proper federation behavior - Accept activities are still sent for duplicate follows

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Set up a WordPress site with the ActivityPub plugin
* Have an ActivityPub account (e.g., from Mastodon) follow your WordPress blog
* Note that you receive a "New Follower" email notification
* Have the same account send another follow request (or wait for automatic retries from instances like Bonfire)
* Verify that you do NOT receive another email notification for the same follower
* Check that the follower still appears in your followers list
* Run the test suite with `npm run env-test` to verify the new test passes

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [x] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Prevent duplicate email notifications for existing followers.

</details>

### CODE REVIEW

File: includes/handler/class-follow.php [hunk 1]
```diff
@@ -40,13 +41,18 @@ public static function handle_follow( $activity, $user_ids ) {
...
+		if ( ! \is_wp_error( $existing_actor ) ) {
+			$already_following = Followers::follows( $existing_actor->ID, $user_id );
+		}
+
 		// Save follower.
-		$remote_actor = Followers::add(
-			$user_id,
-			$activity['actor']
-		);
+		$remote_actor = Followers::add( $user_id, $activity['actor'] );
```
Comment (pfefferle) [inline includes/handler/class-follow.php]: With that check in place, we can skip the Follow process when `$already_following` is `true`!?

```suggestion
		if ( ! $already_following ) {
			$remote_actor = Followers::add( $user_id, $activity['actor'] );
		}
```

Comment (obenland) [reply includes/handler/class-follow.php]: Fixed in [f67c6f4](https://github.com/Automattic/wordpress-activitypub/pull/2452/commits/f67c6f49e49d4b253865e52d734b77bd147df09c).

**Review by pfefferle — APPROVED** [review]
