### PR TITLE
Embed: Check it's an activity object before using it

### LINKED ISSUE #1641: Undefined array key in class-embed.php
### Quick summary

```
Warning at shkspr.mobi/blog/wp-admin/admin-ajax.php?action=oembed-cache&post=32092:
[2] Undefined array key "id" in /wp-content/plugins/activitypub/includes/class-embed.php on line 108
```

https://github.com/Automattic/wordpress-activitypub/blob/7837721dc479d9a6d73e4f14b80ff16c30fd2134/includes/class-embed.php#L108

### Steps to reproduce

No idea. Just started seeing it in my logs.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

I'm not sure why this function is being called. I have a normal oEmbed representation of my posts.

The post itself is fairly old, but was edited recently - `https://shkspr.mobi/blog/?p=32092`

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1641.

I have not been able to reproduce the notice described in #1641. Adding a check to make sure we're dealing with an activity object before using it, should account for that scenario, though.

## Proposed changes:

* Checks whether the object returned is an activity object.
* Introduces `is_activity_object()`.
* Adds unit tests.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [ ] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Added a check to make sure we only attempt to embed activity objects, when processing fallback embeds.

</details>

### CODE REVIEW

File: includes/class-embed.php [hunk 1]
```diff
@@ -32,7 +32,8 @@ public static function init() {
 	public static function get_html( $url, $inline_css = true ) {
 		// Try to get ActivityPub representation.
 		$object = Http::get_remote_object( $url );
-		if ( is_wp_error( $object ) ) {
+
+		if ( is_wp_error( $object ) || ! is_activity_object( $object ) ) {
```
Comment (pfefferle) [inline includes/class-embed.php]:
```suggestion
		if ( \is_wp_error( $object ) || ! is_activity_object( $object ) ) {
```

File: includes/functions.php [hunk 2]
```diff
@@ -1579,6 +1587,17 @@ function is_actor( $data ) {
...
 
+	return _is_type_of( $data, $types );
+}
+
+/**
+ * Private helper to check if $data is of a given type set.
+ *
+ * @param array|object|string $data  The data to check.
+ * @param array               $types The types to check against.
+ * @return boolean True if $data is of one of the types, false otherwise.
```
Comment (pfefferle) [inline includes/functions.php]:
```suggestion
 * @param array               $types The types to check against.
 *
 * @return boolean True if $data is of one of the types, false otherwise.
```

File: includes/functions.php [hunk 3]
```diff
@@ -1579,6 +1587,17 @@ function is_actor( $data ) {
...
+ */
+function _is_type_of( $data, $types ) {
```
Comment (pfefferle) [inline includes/functions.php:1601]: why prefixing?

File: includes/functions.php [hunk 4]
```diff
@@ -1547,19 +1547,27 @@ function is_activity( $data ) {
...
+ *
+ * @return boolean True if the `$data` is an Activity Object, false otherwise.
+ */
+function is_activity_object( $data ) {
+	/**
+	 * Filters the activity object types.
+	 *
+	 * @param array $types The activity object types.
+	 */
+	$types = apply_filters( 'activitypub_activity_object_types', Base_Object::TYPES );
```
Comment (pfefferle) [inline includes/functions.php]:
```suggestion
	$types = \apply_filters( 'activitypub_activity_object_types', Base_Object::TYPES );
```

File: includes/functions.php (hunk 3 above)
Comment (obenland) [reply includes/functions.php:1601]: It's WordPress' (imperfect) way to denote a private function that's not part of an API and shouldn't be used outside of Core ([example](https://github.com/WordPress/wordpress-develop/blob/6.8.1/src/wp-includes/cron.php#L1010-L1015)).

Comment (pfefferle) [reply includes/functions.php:1601]: sure but why does it have to be private? we even use private WordPress functions ;)

I would not go that path.

Comment (obenland) [reply includes/functions.php:1601]: It's just a helper function. If this was part of a class I'd make it a private method. In the end nothing changes, prefix or not, people can still use it. But at least they know they shouldn't.

Comment (pfefferle) [reply includes/functions.php:1601]: but why shouldn't they?

**Review by pfefferle — APPROVED** [review]

File: includes/functions.php (hunk 3 above)
Comment (obenland) [reply includes/functions.php:1601]: Because it's a helper function and not part of an API. I think there's a general expectations that functions in this file are fine to be used in third-party plugins. `_is_type_of()` is not part of an API, it's just a helper for the three API functions that use them.

Comment (obenland) [reply includes/functions.php:1601]: Ha! I said the same thing twice 😄
