### PR TITLE
User: Don't fall back to global post when looking for avatar

### LINKED ISSUE #1459: Follow me Block: avatar replaced by attachment image on attachment pages
### Quick summary

On attachment pages, the avatar from the Follow me block is not displayed. Instead, you'll see the attachment itself.

### Steps to reproduce

1. Start with a site where you use a block-based theme like Twenty Twenty Five
2. Go to Appearance > Editor
3. Select the Single Posts template, and add a Follow me block somewhere on the page, e.g. above the post content.
4. Save your changes
5. Go to Media > Add New
6. Upload a new image
7. Note the image ID that is created as the upload completes
8. Go to `https://yoursite.com/?p=xxxx`, `xxxx` being the image ID.
    * You'll see that the attachment image is displayed in the block.

Here is an example:

* Post with an image -> the Follow me block is nicely displayed
https://herve.bzh/20250314-70338/

Image

* Attachment page -> the Follow me block is not displayed properly
https://herve.bzh/20250314-70338/pxl_20250314_1830477002/

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1459.

## Proposed changes:

* Makes sure there's a value before checking whether it's an image.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* See reproduction steps in #1459.
* Make sure the correct avatar is showing.

### CODE REVIEW

File: tests/includes/class-test-move.php [hunk 1]
```diff
@@ -78,7 +78,7 @@ public function test_account_with_invalid_user() {
 	 */
 	public function test_account_with_invalid_target() {
 		$from = Actors::get_by_id( self::$user_id )->get_id();
-		$to   = 'https://invalid-url.com/user/1';
+		$to   = 'https://example.com/user/1';
```
Comment (obenland) [inline tests/includes/class-test-move.php:81]: I kept getting `wp_validate_url()` errors when running tests locally, not sure why?

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢
