### PR TITLE
Interactions: Don't show likes and reposts for comments

### LINKED ISSUE #1498: Reactions: Likes and Reposts of comments are stored for main post
### Quick summary

When someone Likes or reposts a federated comment on one of your posts, that reaction is stored for the main post.

### Steps to reproduce

1. Publish a new post.
2. Have someone reply to that post ; their reply will appear as a comment on your site.
3. Reply to their comment from your site ; your reply will be federated as expected.
4. Now have someone Like or Repost this reply
    * You will receive a notification email that your **post** was Liked / boosted
    * The Reactions block will show that reaction on the post, even though that was your reply down in the comments that was Liked / boosted.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1498.

## Proposed changes:

* Saves parent comment id when a reaction to a comment is received.
* Adds check for parent comment id being `0` when querying for reactions.
* Updates reaction notification email body
* Adds unit test.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Publish a new post.
* Have someone reply to that post ; their reply will appear as a comment on your site.
* Reply to their comment from your site ; your reply will be federated as expected.
* Now have someone Like or Repost this reply.
* Make sure it does not get added to the reactions in the Reaction block.

#### After
image

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [x] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [ ] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Likes and Reposts for comments to a post are no longer attributed to the post itself.

</details>

### CODE REVIEW

**Comment by pfefferle** [comment]
Why shouldn't we collect them? I think this is more an issue of how we show the reactions for the output as a storing/collecting issue.

Even if we merge this PR, I think we also have to improve the output by ignoring all reactions that have a `comment_parent`, to prevent that we do not have the same issue when working on comment-reactions.

**Comment by obenland** [comment]
Yeah that's a good point, maybe we should start there. We should probably also check wording in the notification email

File: includes/collection/class-interactions.php [hunk 1]
```diff
@@ -113,16 +107,19 @@ public static function add_reaction( $activity ) {
...
 
-		$comment_content = $comment_type['excerpt'];
+		$comment_data = self::activity_to_comment( $activity );
+		if ( ! $comment_data ) {
+			return false;
+		}
 
 		$comment_data['comment_post_ID']           = $comment_post_id;
-		$comment_data['comment_content']           = \esc_html( $comment_content );
+		$comment_data['comment_parent']            = $parent_comment_id ? $parent_comment_id : 0;
```
Comment (pfefferle) [inline includes/collection/class-interactions.php:121]: oh no! this wasn't done before!?! 😱

Comment (obenland) [reply includes/collection/class-interactions.php:121]: 😬

Comment (pfefferle) [reply includes/collection/class-interactions.php:121]: that explains a lot!!!

File: includes/class-mailer.php [hunk 2]
```diff
@@ -88,8 +88,26 @@ public static function comment_notification_text( $message, $comment_id ) {
...
+		} else {
+			$parent_comment = \get_comment( $comment->comment_parent );
+			$notify_message = \sprintf(
+				/* translators: 1: Comment type, 2: Post title, 3: Parent comment author */
+				\html_entity_decode( esc_html__( 'New %1$s on your post &#8220;%2$s&#8221; in reply to %3$s&#8217;s comment.', 'activitypub' ) ),
+				\esc_html( $comment_type['singular'] ),
+				\esc_html( $post->post_title ),
+				\esc_html( $parent_comment->comment_author )
+			) . PHP_EOL . PHP_EOL;
+		}
```
Comment (pfefferle) [inline includes/class-mailer.php:109]: should we simply skip the else mail, because we do not show them yet?

Comment (obenland) [reply includes/class-mailer.php:109]: They're no longer shown in the frontend but they still get saved and are visible in the Comments list. They'll probably also require moderation (although I've not tested that). I'm not sure if it would be more or less confusing to notify about them, tbh. What do you think?

**Review by pfefferle — APPROVED** [review]
