### PR TITLE
Site Health: Fix issue 1545 and add some additional informations

### LINKED ISSUE #1545: Critical error caused by class-health-check.php
After logging in to my WP blog and updating the ActivityPub plugin, I'm seeing a "critical error" being mentioned on the site health page, and even received an error message including the following stack trace (redacted) via mail:

```
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 278 der Datei /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-content/plugins/activitypub/includes/wp-admin/class-health-check.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined method WP_Error::get_url() in /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-content/plugins/activitypub/includes/wp-admin/class-health-check.php:278
Stack trace:
#0 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-includes/class-wp-hook.php(324): Activitypub\WP_Admin\Health_Check::debug_information()
#1 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-admin/includes/class-wp-debug-data.php(135): apply_filters()
#3 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-admin/site-health-info.php(36): WP_Debug_Data::debug_data()
#4 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-admin/includes/class-wp-site-health.php(68): require_once('/xxxxxxxxx/xx/x...')
#5 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-includes/class-wp-hook.php(324): WP_Site_Health->show_site_health_tab()
#6 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /xxxxxxxxx/xx/xxxxxxxxx/htdocs/de_example_www/wp-admin/site-health.php(220): do_action()
#9 {main}
  thrown
```

I updated the AP plugin from a version `<5.6.0` to `5.6.1`, but don't know if this error was caused by the old or new plugin version. I can see that the relevant lines have been touched recently - blame points at #1487 - but I can't tell if my error is the one that was fixed, or another one introduced by the fix.

In any case, I do not know how to proceed, because my site health page seems to be stuck at displaying just this error message but nothing else. The blog itself seems to be unaffected. If this is something I can fix on my end, any pointers would be welcome.

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes #1545

## Proposed changes:

* Fixed #1545
* Fixed a PHP Warning
* Added `actor_mode`, `object_type`, `post_template` and `authorized_fetch` debug informations

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to the debug tab on the site health page

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [X] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Fixed some some bugs and added additional informations on the Debug tab of the Site-Health page.

</details>

### CODE REVIEW

File: includes/wp-admin/class-health-check.php [hunk 1]
```diff
@@ -263,27 +263,55 @@ public static function is_webfinger_endpoint_accessible() {
...
-					'value'   => $actor->get_url(),
-					'private' => false,
-				),
-				'author_id'  => array(
-					'label'   => __( 'Author ID', 'activitypub' ),
-					'value'   => $actor->get_id(),
-					'private' => false,
-				),
-			),
+		if ( $actor && ! is_wp_error( $actor ) ) {
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php:273]: Maybe we could still show these rows, but with an empty value or a message that we couldn't get that information because the current user doesn't have a Fediverse profile?

Comment (obenland) [reply includes/wp-admin/class-health-check.php:273]: Never mind, I think this is good as-is.

**Review by obenland — APPROVED** [review]
