### PR TITLE
Return proper ID instead of object

### LINKED ISSUE #101220: Content Carousel/Blog Posts block: posts don't show up in the front-end when Fediverse is enabled
### Context and steps to reproduce

1. Create a new post or page
2. Add the Content Carousel block
3. Enable Fediverse under Tools > Marketing > Connections
4. Check the initial results on the frontend.
5. Go back to the initial page and set the number of items to 30
6. Check again. There should be no posts displayed

PS: Make sure you use an FSE theme. In my tests, I used Alonso.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

A workaround would be to:
- Disable Fediverse
- Remove the Fediverse block from the template
- Reduce the number of items shown on the block to 10-12. Going up in number will decrease the number of posts shown on the frontend.

### Platform

Simple

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes https://github.com/Automattic/wp-calypso/issues/101220
Also:
* Ensure that Query::get_object_id() returns an ID instead of an Object.
* Improved and simplified Query code

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

File: includes/class-activitypub.php [hunk 1]
```diff
@@ -123,7 +123,7 @@ public static function uninstall() {
 	 * @return string The new path to the JSON template.
 	 */
 	public static function render_activitypub_template( $template ) {
-		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
+		if ( wp_is_serving_rest_request() || wp_doing_ajax() ) {
```
Comment (obenland) [inline includes/class-activitypub.php:126]: I'm afraid `wp_is_serving_rest_request()` is not compatible with our min WP version of 6.4. We could add a compat for it?

**Review by marabalmadena — COMMENTED** [review]
⁦m‍a‍r‍i‍b‍s‍a‍n‍i‍t‍a‍t‍i‍o‍n‍.‍w‍o‍r‍d‍p‍r‍e‍s‍s‍.‍c‍o‍m⁩

**Comment by marabalmadena** [comment]
⁦m‍a‍r‍i‍b‍s‍a‍n‍i‍t‍a‍t‍i‍o‍n‍.‍w‍o‍r‍d‍p‍r‍e‍s‍s‍.‍c‍o‍m⁩

**Review by obenland — APPROVED** [review]
