### PR TITLE
Fix #1970

### LINKED ISSUE #1970: Uncaught Error: Call to undefined method WP_Error::get_icon()
### Quick summary

Overview of the Follower in the Plugin Options page is broken.
Following PHP error comes up.

Uncaught Error: Call to undefined method WP_Error::get_icon()
in /www/htdocs/.../wp-content/plugins/activitypub/includes/table/class-followers.php on line 127

See enclosed screenshot.

Image

### Steps to reproduce

1. Open Plugin Options
2. Open Follower Section

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes #1970 

## Proposed changes:

* Check if Actor transformation was properly executed and skip Actor element if not
* Add error to Actor object
* Improve cleanup method, to update Actor if remote request returns valid JSON

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Add a follower/following
* Edit DB entry to a broken JSON
* Load follower/following table

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Fixed a PHP error that prevented the Follower overview from loading.

</details>

### CODE REVIEW

File: includes/table/class-followers.php [hunk 1]
```diff
@@ -199,7 +199,13 @@ public function prepare_items() {
 		);
 
 		foreach ( $followers as $follower ) {
-			$actor     = Actors::get_actor( $follower );
+			$actor = Actors::get_actor( $follower );
+
+			if ( \is_wp_error( $actor ) ) {
+				Actors::add_error( $follower->ID, $actor );
```
Comment (obenland) [inline includes/table/class-followers.php]: Should we add the error inside of `Actors::get_actor()` when we return an error, rather than having calling code be responsible for it?

Comment (pfefferle) [reply includes/table/class-followers.php]: good point!

File: includes/collection/class-actors.php [hunk 2]
```diff
@@ -702,9 +702,11 @@ public static function get_actor( $post ) {
 		$post = \get_post( $post );
 
 		if ( ! $post ) {
+			$text = \__( 'Actor not found', 'activitypub' );
+			self::add_error( $post->ID, $text );
```
Comment (obenland) [inline includes/collection/class-actors.php]: yeah, without a `$post`, this won't work. Let's just limit it to the `init_from_json()` case you added below.

Comment (pfefferle) [reply includes/collection/class-actors.php]: oh :D

**Review by obenland — APPROVED** [review]
