### PR TITLE
Fixes PHP warnings and remote delete

### LINKED ISSUE #463: PHP Deprecated
### Quick summary

While editing and publishing posts on WP 6.3.1 with AP 1.01, many lines like this one below appear in my PHP www-error-log (PHP 8.1.16)

PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/activitypub/includes/class-signature.php on line 244

### Steps to reproduce

Edit/Publish post in WP.

### What you expected to happen

See error

### What actually happened

See error

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes #463 and remote deletes (mentioned in #465 )

## Proposed changes:

*

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

1. write a new post
2. wait for it to be published on the fediverse
3. delete the post
4. check if post is deleted on all remote platforms

### CODE REVIEW

File: includes/class-signature.php [hunk 1]
```diff
@@ -240,8 +240,11 @@ public static function verify_http_signature( $request ) {
 			}
 
 			// fix route for subdirectory installs
-			$path = wp_parse_url( get_home_url(), PHP_URL_PATH );
-			$path = trim( $path, '/' );
+			$path = \wp_parse_url( \get_home_url(), PHP_URL_PATH );
+
+			if ( \is_string( $path ) ) {
+				$path = trim( $path, '/' );
```
Comment (mediaformat) [inline includes/class-signature.php:246]: We might also use `wp_unslash()` if needed
