### PR TITLE
Reactions: Fix fallback for blocks with default title

### LINKED ISSUE #1704: Did 5.9.0 break Fediverse reactions block?
### Quick summary

Fediverse Reactions are no longer displayed on blog index or individual posts, and the formatting in the template previews look strange (screenshot attached)

### Steps to reproduce

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Critical

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1704.

## Proposed changes:

* Changes the markup for Reaction blocks without inner content.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [x] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Fixed a bug where Reaction blocks without modified titles did not get displayed correctly.

</details>

### CODE REVIEW

**Review by pfefferle — DISMISSED** [review]
untested but lgtm!

**Review by jeherve — COMMENTED** [review]
This fixed it for me!

One thing I've noticed, though, is that we now always display the heading on the frontend, even when we have no reactions. That seems to be a regression.

**Comment by obenland** [comment]
What a nightmare. Let's hope this can be remedied when we convert it to using the Interactivity API.

File: includes/class-blocks.php [hunk 1]
```diff
@@ -186,8 +186,21 @@ public static function render_post_reactions_block( $attrs, $content ) {
 		}
 
 		$args = array( 'data-attrs' => wp_json_encode( $attrs ) );
-		if ( isset( $attrs['title'] ) ) {
-			$args['class'] = 'activitypub-reactions-block';
+		if ( empty( $content ) ) {
+			if ( isset( $attrs['title'] ) ) {
+				$content = '<div class="activitypub-reactions"><div class="activitypub-reactions-block" ' . \get_block_wrapper_attributes( $args ) . '></div></div>';
+			} else {
+				$has_comments = \get_comments(
```
Comment (jeherve) [inline includes/class-blocks.php:193]: Should this be checked even if you have a custom reactions block title?

Comment (obenland) [reply includes/class-blocks.php:193]: In the case of a custom title `view.js` handles displaying that. However there's no good way to determine whether it uses a heading block or not from in there. At least not in this version of the block.

**Review by pfefferle — APPROVED** [review]
I have no idea if that is the best way to go, but it seems to work and we should fix that asap.
