### PR TITLE
Check if the current post type supports ActivityPub.

### LINKED ISSUE #521: Pages show in ActivityPub despite being disabled (in a weird way)
### Quick summary

I have checked ActivityPub only for Posts (not Pages or media).
When I do an activity-Pub search for a Page it still shows up, but with all the [ap_*] fields being empty. The other custom fields and the page thumbnail are still populated.

### Steps to reproduce

1. Search for https://le-chat-a-velo.at/reisen/karpatenbecken-2023/ in on a mastodon server.

### What you expected to happen

i'd expect either the full content (since it is still publically avaliable) or a not found response (since pages are disabled)

### What actually happened

image

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Fixes #521 

## Proposed changes:

* Check if post type is supported by ActivityPub

### CODE REVIEW

File: includes/functions.php [hunk 1]
```diff
@@ -279,6 +279,20 @@ function is_activitypub_request() {
...
+		$queried_object = \get_queried_object();
+		$post_type      = \get_post_type( $queried_object );
+		$post_types     = \get_post_types_by_support( 'activitypub' );
+
+		if (
+			false === $post_type ||
+			! \in_array( $post_type, $post_types, true )
+		) {
+			return false;
+		}
```
Comment (jeherve) [inline includes/functions.php:293]: Once you have the post type, I think you may be able to rely on `post_type_supports`:

```suggestion
		return ! empty( $post_type ) && \post_type_supports( $post_type, 'activitypub' );
```

Comment (pfefferle) [reply includes/functions.php:293]: thanks for the feedback, but I still have to rewrite it a bit, to only return on `false`.

**Review by mattwiebe — APPROVED** [review]
Looks good to me

**Review by jeherve — APPROVED** [review]
