### PR TITLE
Filter comment federation by comment type

### LINKED ISSUE #2492: Notes feature in WordPress 6.9 causes site pings
### Quick summary

When a user creates a Note using the new feature added in WordPress 6.9, the site receives a a `[Create]` post in their inbox.

It appears that the post status of the post does not matter. I have reproduced it with a post in the published and draft state. Under the hood, Notes are just `WP_Comment` of the `note` comment type. In Core, the `note` comment type is excluded from queries unless `all` is passed to the related functions, or `note` is explicitly specified. The plugin likely just needs some adjustments to exclude notes by default as well.

### Steps to reproduce

1. Create a post.
2. Focus on a block.
3. Click Options on the block toolbar.
4. Select Add Note.
5. Type a note and click the Add Note button.
6. Observe an item in the site's inbox.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Only federate comments with supported comment types to prevent federation of special comment types like pingbacks, trackbacks, and custom types that should not be published to the fediverse.

Fixes #2492

## Proposed changes:
- Add comment type filtering to Comment scheduler
- Only allow registered ActivityPub comment types and standard WordPress comment types (empty string and 'comment')
- Add test cases for unsupported comment types ('note' and 'custom_unsupported_type')
- Fix test assertion to properly query outbox items by object ID meta instead of post title

### Other information:

- [X] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Prevents unwanted comment types—like pingbacks, trackbacks, notes and custom system comments, from being federated, ensuring only real user comments are shared with the fediverse.

</details>

### CODE REVIEW

File: includes/scheduler/class-comment.php [hunk 1]
```diff
@@ -51,6 +51,21 @@ public static function schedule_comment_activity( $new_status, $old_status, $com
...
 
+		/*
+		 * Check against supported comment types.
+		 * Only federate registered ActivityPub comment types and standard WordPress comments.
+		 */
+		$allowed_types = Comment_Utils::get_comment_type_slugs();
+
+		// Add core WordPress comment types.
+		$allowed_types[] = ''; // Empty string is default WordPress comment type.
+		$allowed_types[] = 'comment'; // Some plugins/themes use 'comment'.
```
Comment (obenland) [inline includes/scheduler/class-comment.php]: I don't know if it's important, but `''` is the legacy way of denoting a `comment`, `'comment'` is [how Core saves them now](https://github.com/WordPress/wordpress-develop/commit/d5a7a3a45dc18ad1554e185c6611ec54ced9b40c).

Comment (pfefferle) [reply includes/scheduler/class-comment.php]: sure, but I think we have tests for empty post-type... I can update the tests though!?

Comment (obenland) [reply includes/scheduler/class-comment.php]: Sorry, this was in reference to the inline comments explaining these entries. They're incorrect.

I'd be happy for us to correct them or remove, either is fine with me.

File: includes/scheduler/class-comment.php [hunk 2]
```diff
@@ -51,6 +51,24 @@ public static function schedule_comment_activity( $new_status, $old_status, $com
...
 		}
 
+		/*
+		 * Check with supported comment types.
+		 * Only federate registered ActivityPub comment types and standard WordPress comments.
+		 */
+		$allowed_types = Comment_Utils::get_comment_type_slugs();
+		if ( ! is_array( $allowed_types ) ) {
+			$allowed_types = array();
+		}
```
[the remark this answers is not in the document]
Comment (obenland) [reply includes/scheduler/class-comment.php]: @pfefferle This looks to be good feedback, no?

[the remark this answers is not in the document]
Comment (pfefferle) [reply includes/scheduler/class-comment.php]: grrr! I already accepted these changes, but claude braught them back!!!

**Review by obenland — APPROVED** [review]
