### PR TITLE
Fix site-health check

### LINKED ISSUE #1464: https://myauthorurl does not return valid JSON
### Quick summary

WordPress 6.7.2
ActivityPub 5.4.1

Since today I see the error:

“Your author URL https://myauthorurl does not return valid JSON for application/activity+json. Please check if your hosting supports alternate Accept headers.”

### Steps to reproduce

This error appeared overnight without me knowing why.
As a test, I've deactivated the cache (totalcache plugin) but this doesn't solve my problem.

Anthony

### Severity

Minor (?)

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Properly check if the Actor-ID is accessible. This PR checks with all required headers and the signature, to also support AUTHORIZED_FETCH.

Fixes #1464

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Run all Site-Health checks with the required headers and a valid signature.

</details>

### CODE REVIEW

File: includes/wp-admin/class-health-check.php [hunk 1]
```diff
@@ -177,78 +177,22 @@ public static function test_webfinger() {
 	 * @return bool|WP_Error True if the author URL is accessible, WP_Error otherwise.
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php]:
```suggestion
	 * @return bool|\WP_Error True if the author URL is accessible, WP_Error otherwise.
```
The docs for `is_webfinger_endpoint_accessible()` would need to be updated like that, too

File: includes/wp-admin/class-health-check.php [hunk 2]
```diff
@@ -177,78 +177,22 @@ public static function test_webfinger() {
...
-					\__(
-						'Your author URL <code>%s</code> was replaced, this is often done by plugins.',
-						'activitypub'
-					),
-					$author_url
-				)
-			);
-		}
+		$user  = \wp_get_current_user();
+		$actor = Actors::get_by_id( $user->ID );
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php]:
```suggestion
		$actor = Actors::get_by_id( \wp_get_current_user_id() );
```

File: includes/wp-admin/class-health-check.php [hunk 3]
```diff
@@ -312,46 +256,16 @@ public static function is_webfinger_endpoint_accessible() {
...
-
 	/**
 	 * Static function for generating site debug data when required.
 	 *
 	 * @param array $info The debug information to be added to the core information page.
 	 * @return array The filtered information
 	 */
 	public static function debug_information( $info ) {
+		$user  = \wp_get_current_user();
+		$actor = Actors::get_by_id( $user->ID );
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php]:
```suggestion
		$actor = Actors::get_by_id( \wp_get_current_user_id() );
```

**Review by obenland — APPROVED** [review]
