### PR TITLE
Comments: Show @-mentions in line with reply

### LINKED ISSUE #1135: Comment replies via Federation: @mention in Federated reply is wrapped in a paragraph
### Quick summary

This is a follow-up to #844, and its fix #1086. The added @mention works well, but for some reason a paragraph is added around the mention, breaking the mention into its own line.

Here is an example:

- Reply on my site: https://herve.bzh/20250107-15467/#comment-173
- Reply on the Fediverse, including a line break: https://mastodon.social/@inkican/113789796331971211
- ActivityPub representation including the line break: https://herve.bzh/?c=173&activitypub
`<p><a class="u-mention mention" href="https://mastodon.social/@inkican">@inkican@mastodon.social</a></p><p>I&rsquo;ll add it to my « To read » list, thank you! 🙂</p>`

### Steps to reproduce

1. Publish a post
2. Have another comment reply to the post on the Fediverse
3. On your site, reply to the comment via Federation
4. View the reply in the Fediverse client

### What you expected to happen

I would expect the reply to include a @mention of the person I'm replying to, immediately followed by my reply.

### What actually happened

Instead the @mention is followed by a line break.

### Impact

All

### Available workarounds?

There is no user impact

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1135.

@pfefferle Any reason the mention handling shouldn't be part of `get_content()`? Is there a use case for it that requires it to not contain Fediverse mentions?

## Proposed changes:

* Prepends mentions to comment content without wrapping paragraph tags.
* Moves @-mention handling into the comment content getter to avoid grepping HTML tags to insert them in the right place.
* Updates unit tests to test for the new expected output.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Publish a post.
* Have another comment reply to the post on the Fediverse.
* On your site, reply to the comment via Federation.
* View the reply in the Fediverse client and make sure the reply is inline with the mentions.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I'll say that this tests well on my site, but I'll let @pfefferle weigh in for your question. :)

File: includes/transformer/class-comment.php [hunk 1]
```diff
@@ -107,8 +90,18 @@ protected function get_attributed_to() {
...
 	protected function get_content() {
-		$comment = $this->wp_object;
-		$content = $comment->comment_content;
+		$comment  = $this->wp_object;
+		$content  = $comment->comment_content;
+		$mentions = '';
+
+		foreach ( $this->extract_reply_context() as $acct => $url ) {
+			$mentions .= sprintf(
+				'<a class="u-mention mention" href="%s">%s</a> ',
```
Comment (pfefferle) [inline includes/transformer/class-comment.php]: Unify HTML with mentions HTML

```suggestion
				'<a rel="mention" class="u-url mention" href="%s">%s</a> ',
```

File: tests/includes/transformer/class-test-comment.php [hunk 2]
```diff
@@ -89,7 +89,7 @@ public function test_content_with_reply_context() {
 		$content = $object->get_content();
 
 		// Test that reply context is added.
-		$this->assertEquals( '<p><a class="u-mention mention" href="https://example.net/@remote">@remote@example.net</a> <a class="u-mention mention" href="https://remote.example/@author">@author@remote.example</a></p><p>This is a comment</p>', $content );
+		$this->assertSame( '<p><a class="u-mention mention" href="https://example.net/@remote">@remote@example.net</a> <a class="u-mention mention" href="https://remote.example/@author">@author@remote.example</a> This is a comment</p>', $content );
```
Comment (pfefferle) [inline tests/includes/transformer/class-test-comment.php]:
```suggestion
		$this->assertSame( '<p><a rel="mention" class="u-url mention" href="https://example.net/@remote">@remote@example.net</a> <a rel="mention" class="u-url mention" href="https://remote.example/@author">@author@remote.example</a> This is a comment</p>', $content );
```

**Review by pfefferle — APPROVED** [review]
@obenland thanks a lot, this should work totally fine! I have simplified the code a bit more and changed the HTML to unify with the one from the mention class.
