### PR TITLE
Fix multibyte character corruption in post summaries

### LINKED ISSUE #1948: Federated post excerpts break for non-English languages (e.g., Korean, Greek)
### Quick summary

Federated posts from WordPress using ActivityPub appear to break or render improperly when the content is in non-English languages. This particularly affects the excerpt or summary portion, which ends up malformed or unreadable on federated platforms such as Mastodon and Misskey.

### Steps to reproduce

1. Create a post in WordPress with non-English (e.g., Korean or Greek) content.
2. Set a custom excerpt manually(or auto).
3. Ensure the site is federated via ActivityPub.
4. Observe how the post appears on federated platforms like Mastodon and Misskey.

---

### **Examples**

**Greek example**

- Post: https://amazingtravelstory.com
- Federation link (Mastodon): https://mastodon.social/@traveller@amazingtravelstory.com/114817668528862094
- Issue: Text appears garbled and malformed.

The excerpt appears broken when viewed from Mastodon. It doesn't appear at all on Misskey, possibly due to compatibility issues with WordPress and Misskey or lack of support for `article` object types.

**Korean example**

- Post: [https://kowporg.wordpress.com/2025/06/11/whats-new-for-developers-june-2025/](https://kowporg.wordpress.com/2025/06/11/whats-new-for-developers-june-2025/)
- Mastodon: [https://mastodon.social/@kowporg.wordpress.com@kowporg.wordpress.com/114664407919655908](https://mastodon.social/@kowporg.wordpress.com@kowporg.wordpress.com/114664407919655908)
- Misskey: [https://misskey.io/notes/a8vesbi0lfbk0pks](https://misskey.io/notes/a8vesbi0lfbk0pks)
- Issue: Content either breaks apart into disjointed paragraphs or includes unexpected HTML artifacts (e.g., rating divs).
- Another Misskey example (broken): [https://misskey.io/notes/aa115go85xvb01p0](https://misskey.io/notes/aa115go85xvb01p0)

* * *

[https://mastodon.social/@kowporg.wordpress.com@kowporg.wordpress.com/114829342235887603](https://mastodon.social/@kowporg.wordpress.com@kowporg.wordpress.com/114829342235887603)  
[https://misskey.io/notes/aa115go85xvb01p0](https://misskey.io/notes/aa115go85xvb01p0)  
This post only appeared on Misskey after I manually triggered federation in a somewhat hacky way, just to see what might happen.

Excerpt received on Misskey:

```
<div class="cs-rating pd-rating" id="pd_rating_holder_8993032_post_491"></div><br/><p>이 포스?</p>
<p>은 Learn WordPress 콘?</p>
<p>?츠 번역에 기여하고자 하는 분들을 위한 가이드?</p>
<p>니다. 트레이닝 팀 핸드북 일부를 바탕으로 콘?</p>
<p>?츠 번역가(Content Translator)로서 ?</p>
<p>?프 온보딩하는 방법을 설?</p>
<p>합니다. 현재 워크플로우가 완벽하게 수립되어 있지 않으며, 향후 변경될 수 있습니다. 각 파트별 원본 링크를 첨부하여 변경사항을 추적할 수 있도록 했습니다.</p>
<p>1. 시작하기: Learn […]</p>
cw('내용 숨기기')
```
It seems the `<div class="cs-rating...">` might have been injected due to a plugin (Crowd Signal or similar) being enabled on the WordPress site.

In Misskey, the H1 header appears as a line with full-width brackets `【】`. While the excerpt shows up in Mastodon without a `cw` (content warning) field, Misskey wraps the entire article body under `cw('내용 숨기기')`.

---

### **Possible cause**

The issue may relate to character encoding problems in `wpautop()` when dealing with non-English characters, or improper handling of excerpts in the `summary` field when federated.  
It’s also possible that `div` elements or plugin-generated markup (such as Crowdsignal rating shortcodes) are interfering with how excerpts are parsed and displayed.

### Site owner impact

Between 20% and 60% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### **Workaround (partial)**

- Avoid custom excerpts and let the plugin auto-generate them.
- Minimize HTML in the excerpt area.
- Avoid shortcodes or plugin outputs (like ratings) in the excerpt.

* * *

### **Suggested direction**

It would be helpful to investigate how `summary` fields are encoded and whether HTML tags or special characters are filtered/sanitized properly before federation.  
Improved support for multilingual excerpts in federated posts would significantly improve usability for international users.

---

https://wordpress.org/support/topic/excerpt-not-formatted-properly-via-activitypub/

> I’ve created a blog post (in Greek) and used some text as an excerpt. The resulting post in activitypub is not correctly formatted, though. I have no idea what to check here. Any help appreciated!

> It’s the same issue in Korean as well. It seems like something is going wrong specifically with non-English languages. I suspect there might be an encoding or formatting issue when handling foreign-language excerpts in ActivityPub posts.

> the only functionality we use is the autop method of core WordPress to add the paragraphs. I will see if I can run some tests with your text to see where the encoding might break.

https://developer.wordpress.org/reference/functions/wpautop/

---

So yeah, federation handling of long-form posts seems to differ drastically depending on the platform. Misskey's rendering logic seems to require MFM (Markup language For Misskey) for clean display, and that might be a whole separate can of worms.

Even so, I think the broken excerpt issue itself is worth investigating, especially since it seems to affect multiple non-English languages. Hence this issue report.
https://mastodon.social/@kowporg.wordpress.com@kowporg.wordpress.com/114868962596447300

### PR DESCRIPTION
**Pull request by obenland**
Fixes #1948

## Proposed changes:
* Fix character encoding corruption in `generate_post_summary()` function by reordering text processing operations.
* Replace byte-based string functions with multibyte-safe equivalents throughout the codebase.
* Add comprehensive test coverage for Greek text handling.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Create a post with Greek text content like: `Τι μπορεί να σου συμβεί σε μια βόλτα για να αγοράσεις μια βαλίτσα για τα ταξίδια σου; Όλα είναι πιθανά αν έχεις ανοιχτές τις "κεραίες" σου\!`
* Generate a post summary using the ActivityPub functionality
* Verify that Greek characters like "σου" are not corrupted to "σ?"
* Run the test suite: `npm run env-test -- --filter test_generate_post_summary`
* All tests should pass, including the new Greek text test case

### Changelog entry

- [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [x] Patch

#### Type

- [x] Fixed - for any bug fixes

#### Message

Fix multibyte character corruption in post summaries, preventing Greek and other non-ASCII text from being garbled during text processing.

</details>

### CODE REVIEW

**Comment by obenland** [comment]
Thanks for the feedback\! I've addressed the redundant condition issue.

Regarding the magic numbers (12, 0.4, 0.8): I'm keeping these as inline values rather than constants because:

1. **Contextual values**: These are algorithm-specific thresholds for text truncation behavior, not configuration that would be reused elsewhere
2. **Local scope**: They only apply to this specific function's word boundary detection logic
3. **WordPress conventions**: The codebase generally uses inline numeric values for similar algorithm parameters
4. **Comments provide context**: The inline comments clearly explain what each threshold controls

Constants would be more appropriate if these values needed to be configurable or reused across multiple functions.

**Comment by obenland** [comment]
@copilot-pull-request-reviewer Thanks for raising this concern about the processing order\!

However, the current order (tags first, then decode) is actually **correct** and necessary to prevent multibyte character corruption. Here's why:

## The Problem with the Suggested Order:
```php
$content = html_entity_decode( $content, ENT_QUOTES, 'UTF-8' );  // Decode first
$content = wp_strip_all_tags( $content );                       // Strip after - CORRUPTS\!
```

When `wp_strip_all_tags()` processes already-decoded multibyte characters, it can corrupt them because it doesn't handle UTF-8 properly.

## Why Current Order is Safe:
```php  
$content = wp_strip_all_tags( $content );                       // Strip tags first
$content = html_entity_decode( $content, ENT_QUOTES, 'UTF-8' ); // Then decode safely
```

1. **HTML entities in tag attributes** are removed along with the tags - this is expected behavior
2. **HTML entities in content** (like `&quot;`, `&#8220;`) are properly decoded after tag removal  
3. **Multibyte characters stay intact** throughout the process

## Real-world Test:
The Greek text test case proves this works correctly:
- Input: `'Τι μπορεί να σου συμβεί...'` 
- Old order: `σου` → `σ?` (corruption)
- New order: `σου` → `σου` (preserved)

The WordPress core uses this same pattern in many places for the same reason. Entities in tag attributes should be stripped with the tags, while content entities are decoded separately.

File: includes/functions.php [hunk 1]
```diff
@@ -1223,13 +1223,13 @@ function generate_post_summary( $post, $length = 500 ) {
 	}
 
 	$content = \strip_shortcodes( $content );
-	$content = \html_entity_decode( $content );
 	$content = \wp_strip_all_tags( $content );
+	$content = \html_entity_decode( $content, ENT_QUOTES, 'UTF-8' );
```
[the remark this answers is not in the document]
Comment (obenland) [reply includes/functions.php:1227]: Thanks for raising this concern about the processing order!

However, the current order (tags first, then decode) is actually **correct** and necessary to prevent multibyte character corruption. Here's why:

## The Problem with the Suggested Order:
```php
$content = html_entity_decode( $content, ENT_QUOTES, 'UTF-8' );  // Decode first
$content = wp_strip_all_tags( $content );                       // Strip after - CORRUPTS!
```

When `wp_strip_all_tags()` processes already-decoded multibyte characters, it can corrupt them because it doesn't handle UTF-8 properly.

## Why Current Order is Safe:
```php  
$content = wp_strip_all_tags( $content );                       // Strip tags first
$content = html_entity_decode( $content, ENT_QUOTES, 'UTF-8' ); // Then decode safely
```

1. **HTML entities in tag attributes** are removed along with the tags - this is expected behavior
2. **HTML entities in content** (like `&quot;`, `&#8220;`) are properly decoded after tag removal  
3. **Multibyte characters stay intact** throughout the process

## Real-world Test:
The Greek text test case proves this works correctly:
- Input: `'Τι μπορεί να σου συμβεί...'` 
- Old order: `σου` → `σ?` (corruption)
- New order: `σου` → `σου` (preserved)

The WordPress core uses this same pattern in many places for the same reason. Entities in tag attributes should be stripped with the tags, while content entities are decoded separately.

File: includes/functions.php [hunk 2]
```diff
@@ -1223,13 +1223,13 @@ function generate_post_summary( $post, $length = 500 ) {
...
 	$content = \trim( $content );
-	$content = \preg_replace( '/\R+/m', "\n\n", $content );
-	$content = \preg_replace( '/[\r\t]/', '', $content );
+	$content = \preg_replace( '/\R+/mu', "\n\n", $content );
+	$content = \preg_replace( '/[\r\t]/u', '', $content );
 
-	if ( $length && \strlen( $content ) > $length ) {
+	if ( $length && mb_strlen( $content, 'UTF-8' ) > $length ) {
```
Comment (pfefferle) [inline includes/functions.php]:
```suggestion
	if ( $length && \mb_strlen( $content, 'UTF-8' ) > $length ) {
```

**Review by pfefferle — DISMISSED** [review]

**Review by pfefferle — DISMISSED** [review]

File: includes/functions.php [hunk 3]
```diff
@@ -1201,7 +1201,7 @@ function generate_post_summary( $post, $length = 500 ) {
 	 * @param string $excerpt_more The excerpt more.
 	 */
 	$excerpt_more = \apply_filters( 'activitypub_excerpt_more', '[…]' );
-	$length       = $length - strlen( $excerpt_more );
+	$length       = $length - mb_strlen( $excerpt_more, 'UTF-8' );
```
Comment (pfefferle) [inline includes/functions.php]:
```suggestion
	$length       = $length - \mb_strlen( $excerpt_more, 'UTF-8' );
```

Comment (obenland) [reply includes/functions.php]: This is going to be a long morning :smile:

**Review by pfefferle — APPROVED** [review]
