### PR TITLE
Remove "Followed" date

### LINKED ISSUE #1927: ActivityPub Followers
### Quick summary

Unfortunately, I can't tell, if this happened with Release 7.0.1 or already in 7.0.0. But it seems the page

wp-admin/users.php?page=activitypub-followers-list

is confusing the different date attributes of a following account.

The "followed" date seems to display the original account creation date instead of the date this user followed the blog. As well, the "last updated" column appears to be empty.

This looks like a bug to me, as it has been working nicely before. 

### Steps to reproduce

Visit the activitypub-followers-list:

Image

### Site owner impact

More than 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### PR DESCRIPTION
**Pull request by pfefferle**
Now that we use the persistence for following and followers, we can not say for sure if that date is the date of following or followed or simply the date when they were imported through an @-reply.

This PR removes it as quick fix. If we want to have that information, we would need to have it in a separate PR, using a post-meta for example.

Fixes #1927 

## Proposed changes:

* Remove "Followed" date

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Removed follower dates to avoid confusion, as they may not have accurately reflected the actual follow time.

</details>

### CODE REVIEW

File: templates/followers-list.php [hunk 1]
```diff
@@ -16,7 +16,7 @@
 ?>
 <div class="wrap">
 	<?php if ( ! $_tab ) : ?>
-	<h1 class="wp-heading-inline"><?php esc_html_e( 'Author Followers', 'activitypub' ); ?></h1>
+	<h1 class="wp-heading-inline"><?php esc_html_e( 'Followers', 'activitypub' ); ?></h1>
```
Comment (obenland) [inline templates/followers-list.php:19]: ✨

**Review by obenland — APPROVED** [review]
This is good to go as-is. 

Would you want to remove "Modified" as well? It doesn't feel super useful.

**Comment by Jiwoon-Kim** [comment]
As I understand it, we need to separate the account registration date from the date when a follow action occurred. It feels somewhat similar to how Instagram handles account metadata. In the case of Mastodon, you can refer to how relationships are managed here: https://mastodon.social/relationships.

https://misskey.io/@pfefferle@mastodon.social/raw
