### PR TITLE
Fix: Show error if site uses "Almost Pretty Permalink" structure

### LINKED ISSUE #1282: Custom permalink structure that causes core functionality of this plugin to fail?!
### Quick summary

Yesterday I was assisting an association setting up this plugin on their WordPress site.

They used a custom permalink structure like this `/index.php/%year%/%monthnum%/%day%/%postname%/`. 

Until removing the prefix `/index.php` federation was not working.

### Steps to reproduce

New site and set a custom permalink structure like `/index.php/%year%/%monthnum%/%day%/%postname%/`. 

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Critical

### What other impact(s) does this issue have?

Federation is broke for already connected instances until they refrech their cache.

### If a workaround is available, please outline it here.

Removing the hardcoded `index.php` from the permalink structure resolved the issue. But all instances that have cached the old outbox urls are broke till they refresh the cache (at least the ID of the actors is right!).

### PR DESCRIPTION
**Pull request by pfefferle**
Show an error if site uses the old "[Almost Pretty Permalink](https://wordpress.org/documentation/article/customize-permalinks/#almost-pretty-permalinks)" structure. We can not guarantee that the plugin works properly with that setup.

Fix #1282

## Proposed changes:

* Check if pretty permalink format starts with `/index.php`

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to the permalinks settings
* Choose "Custom Structure" and add `/index.php` to the structure
* Check if error shows on ActivityPub settings
* Check if error shows on Site-Health

### Changelog entry

-   [X] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [X] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Added - for new features
-   [ ] Changed - for changes in existing functionality
-   [ ] Deprecated - for soon-to-be removed features
-   [ ] Removed - for now removed features
-   [X] Fixed - for any bug fixes
-   [ ] Security - in case of vulnerabilities

#### Message

Show Site Health error if site uses old "Almost Pretty Permalinks" structure.

</details>

### CODE REVIEW

File: includes/wp-admin/class-health-check.php [hunk 1]
```diff
@@ -432,6 +432,18 @@ public static function test_pretty_permalinks() {
 					esc_url( admin_url( 'options-permalink.php' ) )
 				)
 			);
+		} elseif ( str_starts_with( $permalink_structure, '/index.php' ) ) {
+			$result['status']         = 'critical';
+			$result['label']          = \__( 'ActivityPub does not support the "Almost Pretty Permalinks" structure.', 'activitypub' );
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php]: AI suggestion: "Your permalink structure needs to be updated for ActivityPub to work properly."

File: includes/wp-admin/class-health-check.php [hunk 2]
```diff
@@ -432,6 +432,18 @@ public static function test_pretty_permalinks() {
...
+			$result['badge']['color'] = 'red';
+			$result['description']    = \sprintf(
+				'<p>%s</p>',
+				sprintf(
+					/* translators: %s: Permalink settings URL. */
+					\__( 'ActivityPub needs SEO-friendly URLs to work properly. Please <a href="%s">remove the <code>/index.php</code></a> from your permalink structure.', 'activitypub' ),
```
Comment (obenland) [inline includes/wp-admin/class-health-check.php]: AI suggestion: "Your current permalink structure includes "/index.php" which is not compatible with ActivityPub. Please <a href="%s">update your permalink settings</a> to use a standard format without "/index.php"."

**Review by obenland — APPROVED** [review]
